export default function categories(){
    const categories = [
  { value: "cleaning", label: "Cleaning" },
  { value: "plumbing", label: "Plumbing" },
  { value: "electrical", label: "Electrical Work" },
  { value: "carpentry", label: "Carpentry" },
  { value: "gardening", label: "Gardening" },
  { value: "painting", label: "Painting" },
  { value: "home_repair", label: "Home Repair" },
  { value: "ac_repair", label: "AC / Appliance Repair" },
  { value: "pest_control", label: "Pest Control" },
  { value: "moving", label: "Moving & Packing" },
  { value: "waste_removal", label: "Waste Removal" },
  { value: "delivery", label: "Delivery" },
  { value: "vehicle_repair", label: "Vehicle Repair" },
  { value: "ride_share", label: "Ride Sharing" },
  { value: "cooking", label: "Cooking / Meal Prep" },
  { value: "laundry", label: "Laundry & Ironing" },
  { value: "child_care", label: "Child Care" },
  { value: "pet_care", label: "Pet Care" },
  { value: "elderly_care", label: "Elderly Care" },
  { value: "beauty_services", label: "Beauty & Grooming" },
  { value: "fitness_trainer", label: "Fitness Training" },
  { value: "yoga_instructor", label: "Yoga Instructor" },
  { value: "computer_help", label: "Computer / Tech Support" },
  { value: "web_design", label: "Web Design" },
  { value: "graphic_design", label: "Graphic Design" },
  { value: "digital_marketing", label: "Digital Marketing" },
  { value: "photography", label: "Photography" },
  { value: "content_writing", label: "Content Writing" },
  { value: "accounting", label: "Accounting" },
  { value: "legal_help", label: "Legal Help" },
  { value: "event_help", label: "Event Assistance" },
  { value: "catering", label: "Catering" },
  { value: "decoration", label: "Decoration" },
  { value: "music_band", label: "Music / DJ" },
  { value: "security", label: "Security" },
];

return categories
}